<body>
<header>
    <form action="" method="POST">
        <div class="header-cart">
            <button type="submit" class="btn-cart">
                <img class="img-cart"
                     src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVe5NYRihVDjz5-3l1uGW1WHK_JBEuaUaI2g&usqp=CAU"
                     alt="">
            </button>
        </div>
    </form>
</header>
<h3>Online Shop</h3>
<div class="container">
    <div class="card-deck">
        <?php /** @var TYPE_NAME $products */
        foreach ($products as $product): ?>
            <div class="card text-center">
                <div class="card-header">
                    Hit!
                    <a href="#">
                        <img class="card-img-top"
                             src=<?php echo $product->getImage(); ?> alt="Card image">
                        <div class="card-body">
                            <p class="card-text text-muted"><?php echo $product->getName(); ?></p>
                            <a><h5 class="card-title">Very long item name</h5></a>
                            <div class="card-footer">
                                <?php echo $product->getPrice() . " tng"; ?>
                                <input type="text" placeholder="product_id" name="product_id" hidden=""
                                       value="<?php echo $product->getId(); ?>">
                                <input type="text" placeholder="quantity" name="quantity">
                            </div>
                            <a href="/main">
                                <button type="submit" class="btn">Add to cart</button>
                        </div>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>


<style>
    body {
        font-style: sans-serif;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: none;
    }

    h3 {
        line-height: 3em;
    }

    .card {
        max-width: 16rem;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        font-size: 13px;
        color: gray;
        background-color: white;
    }

    .text-muted {
        font-size: 11px;
    }

    .card-footer {
        font-weight: bold;
        font-size: 18px;
        background-color: white;
    }

</style>